anchor_version = "0.17.0"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[programs.devnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[programs.localnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "ts-mocha -t 1000000 -p tsconfig.json"
nina-upgrade = "anchor upgrade --program-id ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4 ./target/deploy/nina.so"