anchor_version = "0.20.1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/nina.json"

[programs.mainnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[programs.devnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[programs.localnet]
nina = "ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "ts-mocha -t 1000000 -p ./tsconfig.json --provider.cluster localnet -b"
test-with-build = "anchor run build && anchor test ./tests --skip-build --provider.cluster localnet"
nina-upgrade = "anchor upgrade --program-id ninaN2tm9vUkxoanvGcNApEeWiidLMM2TdBX8HoJuL4 ./target/deploy/nina.so"
build = "anchor run build-deps && anchor build"
build-deps = "anchor run build-metaplex"
build-metaplex = "cd ./deps/metaplex/rust && pwd && cargo build-bpf && cd ../../../"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex/rust/target/deploy/metaplex.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex/rust/target/deploy/metaplex_token_metadata.so"
