[package]
name = "nina"
version = "0.1.0"
description = "Nina - A self-publishing protocol"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "nina"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.17.0"
anchor-spl = "0.17.0"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
solana-program = "1.7.11"
thiserror = "1.0"
