name: Lint and Format Check on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  lint-and-format:
    name: Run Lint and Format on /hubs, /sdk, and /web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      # Check out the repository
      - uses: actions/checkout@v1

      # Install Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install your dependencies
      - run: npm ci

      # Run ESLint + Prettier on /hubs
      - run: yarn hubs check-lint-format
      # Run ESLint + Prettier on /sdk
      - run: yarn sdk check-lint-format
      # Run ESLint + Prettier on /web
      - run: yarn web check-lint-format
